=== philipWennerstrom/aiondesolation/AL-Game/data/static_data/events_config/login_events.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="login_events">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="login_event" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence/>
                        <xs:attribute name="id" type="xs:int" use="required"/>
                        <xs:attribute name="name" type="xs:string"/>
                        <xs:attribute name="active" type="xs:int" use="required"/>
                        <xs:attribute name="period_start" type="xs:dateTime" use="required"/>
                        <xs:attribute name="period_end" type="xs:dateTime" use="required"/>
                        <xs:attribute name="attend_type" type="AttendType" use="required"/>
                        <xs:attribute name="attend_num" type="xs:int"/>
                        <xs:attribute name="reward_item" type="xs:int" use="required"/>
                        <xs:attribute name="reward_item_num" type="xs:int" use="required"/>
                        <xs:attribute name="reward_item_expire" type="xs:int"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="AttendType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DAILY"/>
            <xs:enumeration value="ANNIVERSARY"/>
            <xs:enumeration value="CUMULATIVE"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== philipWennerstrom/aiondesolation/AL-Game/data/static_data/events_config/login_events.xml
<?xml version="1.0" encoding="UTF-8"?>
<login_events xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="login_events.xsd">
    <login_event id="1" name="test_attend_reward_01_daily" active="1" period_start="2014-03-01T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="DAILY" attend_num="1" reward_item="188052315"
                 reward_item_num="1" reward_item_expire="1440"/>
    <login_event id="2" name="test_attend_reward_01_cumulative_5day" active="0" period_start="2014-03-01T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="CUMULATIVE" attend_num="5" reward_item="165010001"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="3" name="test_attend_reward_01_cumulative_10day" active="0" period_start="2014-03-01T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="CUMULATIVE" attend_num="10" reward_item="166000120"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="4" name="test_attend_reward_01_cumulative_15day" active="0" period_start="2014-03-01T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="CUMULATIVE" attend_num="15" reward_item="166030005"
                 reward_item_num="1" reward_item_expire="10"/>
    <login_event id="5" name="test_attend_reward_01_cumulative_20day" active="0" period_start="2014-03-01T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="CUMULATIVE" attend_num="20" reward_item="168000118"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="6" name="test_attend_reward_01_cumulative_30day" active="0" period_start="2014-03-01T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="CUMULATIVE" attend_num="30" reward_item="169220032"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="7" name="test_attend_reward_01_anniversary_1??" active="0" period_start="2014-03-01T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="4" reward_item="188052830"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="8" name="test_attend_reward_01_anniversary_2??" active="0" period_start="2014-03-01T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="5" reward_item="188052831"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="9" name="test_attend_reward_02_daily" active="1" period_start="2014-03-15T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="DAILY" attend_num="1" reward_item="166000010"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="10" name="test_attend_reward_02_cumulative_10day" active="0" period_start="2014-03-15T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="CUMULATIVE" attend_num="10" reward_item="166000030"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="11" name="test_attend_reward_02_cumulative_20day" active="0" period_start="2014-03-15T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="CUMULATIVE" attend_num="20" reward_item="166000040"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="12" name="test_attend_reward_02_daily_off" active="0" period_start="2014-03-15T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="DAILY" attend_num="1" reward_item="166000050"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="13" name="test_attend_reward_02_cumulative_5day_off" active="0" period_start="2014-03-15T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="CUMULATIVE" attend_num="5" reward_item="166000060"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="14" name="account_create_anniversary_reward_01month" active="1" period_start="2014-04-01T09:00:00"
                 period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="1" reward_item="188053423"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="15" name="account_create_anniversary_reward_02month" active="1" period_start="2014-04-01T09:00:00"
                 period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="2" reward_item="188053424"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="16" name="account_create_anniversary_reward_03month" active="1" period_start="2014-04-01T09:00:00"
                 period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="3" reward_item="188053425"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="17" name="account_create_anniversary_reward_04month" active="1" period_start="2014-04-01T09:00:00"
                 period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="4" reward_item="188053426"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="18" name="account_create_anniversary_reward_05month" active="1" period_start="2014-04-01T09:00:00"
                 period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="5" reward_item="188053427"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="19" name="account_create_anniversary_reward_06month" active="1" period_start="2014-04-01T09:00:00"
                 period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="6" reward_item="188053428"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="20" name="account_create_anniversary_reward_07month" active="1" period_start="2014-04-01T09:00:00"
                 period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="7" reward_item="188053429"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="21" name="account_create_anniversary_reward_08month" active="1" period_start="2014-04-01T09:00:00"
                 period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="8" reward_item="188053430"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="22" name="account_create_anniversary_reward_09month" active="1" period_start="2014-04-01T09:00:00"
                 period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="9" reward_item="188053431"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="23" name="account_create_anniversary_reward_10month" active="1" period_start="2014-04-01T09:00:00"
                 period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="10" reward_item="188053432"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="24" name="account_create_anniversary_reward_11month" active="1" period_start="2014-04-01T09:00:00"
                 period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="11" reward_item="188053433"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="25" name="account_create_anniversary_reward_12month" active="1" period_start="2014-04-01T09:00:00"
                 period_end="2050-12-31T08:59:59" attend_type="ANNIVERSARY" attend_num="12" reward_item="188053434"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="26" name="account_create_anniversary_reward_21month" active="0" period_start="2014-03-01T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="1" reward_item="166000050"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="27" name="account_create_anniversary_reward_22month" active="0" period_start="2014-03-01T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="2" reward_item="166000050"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="28" name="account_create_anniversary_reward_23month" active="0" period_start="2014-03-01T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="3" reward_item="166000050"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="29" name="account_create_anniversary_reward_24month" active="0" period_start="2014-03-01T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="4" reward_item="166000050"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="30" name="account_create_anniversary_reward_25month" active="0" period_start="2014-03-01T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="5" reward_item="166000050"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="31" name="account_create_anniversary_reward_26month" active="0" period_start="2014-03-01T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="6" reward_item="166000050"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="32" name="account_create_anniversary_reward_27month" active="0" period_start="2014-03-01T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="7" reward_item="166000050"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="33" name="account_create_anniversary_reward_28month" active="0" period_start="2014-03-01T00:00:00"
                 period_end="2014-05-01T00:00:00" attend_type="ANNIVERSARY" attend_num="8" reward_item="166000050"
                 reward_item_num="1" reward_item_expire="0"/>
    <login_event id="34" name="account_create_anniversary_reward_29month" active="0" period_start="2014-03-01T00:00:00"
